### ISSUE TITLE
Properly control platform movement via Arduino

### ISSUE THREAD

**Issue by dn793** [henrymliu/StewartPlatform#3]
Completion criteria:
- the platform is controlled by the Arduino
- the movement pattern is matched to actuator parameters
- platform movement matches the expected movement pattern
- hard-coding or pre-programmed pathing is acceptable (corner cases can be avoided)

Validation criteria:
- movement is as intended
- visible performance (noticeable movement/speed)

**Comment by henryymliu** [comment]
Also solved by #11?
